apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring-boot-d
  labels:
    app: demo-spring-boot
spec:
  selector:
    matchLabels:
      app: demo-spring-boot
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-spring-boot
    spec:
      containers:
      - name: demo-spring-boot
        image: dperezcabrera/demo-spring-boot:0.0.1
        ports:
        - containerPort: 8080