apiVersion: v1
kind: Service
metadata:
  name: demo-spring-boot-svc
  labels:
     app: demo-spring-boot
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30000
    protocol: TCP
  selector:
     app: demo-spring-boot

