apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: demo-postgres
    app: demo
  name: demo-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service: demo-postgres
      app: demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        demo-network: "true"
        service: demo-postgres
        app: demo
    spec:
      containers:
      - name: demo-postgres
        image: postgres:12-alpine
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: demo-configmap
              key: DB_NAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secrets
              key: DB_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: demo-configmap
              key: DB_USERNAME
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: demo-postgres-data
      restartPolicy: Always
      volumes:
      - name: demo-postgres-data
        persistentVolumeClaim:
          claimName: demo-postgres-data
